name: Auto Merge Down

# 手动触发或者特定条件下触发，避免无限循环
on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch to merge from'
        required: true
        default: 'main'
        type: choice
        options:
        - main
        - beta
  
  # 只在特定标签发布后触发，避免每次 release 都触发
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  merge-down:
    name: Merge Down
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine source branch
        id: branch
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "source=${{ github.event.inputs.source_branch }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "release" ]; then
            # 从 release tag 判断来源分支
            TAG_NAME="${{ github.event.release.tag_name }}"
            if [[ "$TAG_NAME" == *"-alpha."* ]]; then
              echo "source=alpha" >> $GITHUB_OUTPUT
            elif [[ "$TAG_NAME" == *"-beta."* ]]; then
              echo "source=beta" >> $GITHUB_OUTPUT
            else
              echo "source=main" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Merge main to beta and alpha
        if: steps.branch.outputs.source == 'main'
        run: |
          # Merge main to beta
          git checkout beta
          git pull origin beta
          git merge main --no-ff -m "chore: merge main into beta [skip ci]"
          git push origin beta
          
          # Merge main to alpha
          git checkout alpha
          git pull origin alpha  
          git merge main --no-ff -m "chore: merge main into alpha [skip ci]"
          git push origin alpha

      - name: Merge beta to alpha
        if: steps.branch.outputs.source == 'beta'
        run: |
          git checkout alpha
          git pull origin alpha
          git merge beta --no-ff -m "chore: merge beta into alpha [skip ci]"
          git push origin alpha
          
      - name: No downstream merge needed
        if: steps.branch.outputs.source == 'alpha'
        run: |
          echo "Alpha branch has no downstream branches to merge to"